/**
 * Write both prompt registries out as JSON, so the report generator and the
 * ledger read the same version metadata the trial runs use, and so a refactor of
 * either registry can be proved harmless by diffing the dump before and after.
 * The registries stay the single home; these are projections of them.
 *
 * Usage: pnpm exec tsx dump-versions.mts
 */

import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { GROUP_PROMPTS } from "./group-prompts.mts";
import { SPLIT_PROMPTS } from "./split-prompts.mts";

/**
 * Write one registry's projection beside the scripts.
 *
 * @param options - Options object.
 * @param options.name - The file to write, such as `group-versions.json`.
 * @param options.versions - The projected versions, already built.
 * @returns Nothing.
 */
async function dump({
	name,
	versions,
}: {
	readonly name: string;
	readonly versions: readonly Record<string, unknown>[];
}): Promise<void> {
	await writeFile(join(import.meta.dirname, name), JSON.stringify(versions, null, 2), "utf8");
	console.log(`${name} written`);
}

await dump({
	name: "group-versions.json",
	versions: GROUP_PROMPTS.map((version) => ({
		id: version.id,
		summary: version.summary,
		changed: version.changed,
		promptWithLabels: version.build({ labelsShown: true }),
		promptWithoutLabels: version.build({ labelsShown: false }),
	})),
});

await dump({
	name: "split-versions.json",
	versions: SPLIT_PROMPTS.map((version) => ({
		id: version.id,
		summary: version.summary,
		changed: version.changed,
		prompt: version.build(),
	})),
});

/** Where the readable copies of the markdown splitting prompts are published. */
const DOCS_DIR = join(import.meta.dirname, "..", "..");

/**
 * Also write every markdown-form splitting prompt out as a `.md` document.
 *
 * Such a version IS a markdown document — that is the whole of what makes it
 * what it is — so a `.md` file is the form it is meant to be read in. Which
 * versions qualify is read off the prompt itself rather than listed here, so
 * adding the next one publishes it without touching this script. Generated
 * rather than hand-written for the reason the ledger is: `split-prompts.mts` is
 * the single home, and a hand-kept copy would drift from the text actually sent.
 */
for (const version of SPLIT_PROMPTS) {
	const prompt = version.build();
	if (!prompt.startsWith("# ")) {
		continue;
	}
	const name = `split-prompt-${version.id}.md`;
	await writeFile(
		join(DOCS_DIR, name),
		[
			"<!--",
			"Generated by docs/quality/segmentation-prototype/dump-versions.mts.",
			"Do not edit by hand: the text sent to the model comes from SPLIT_PROMPTS in",
			"split-prompts.mts, and a version is never edited once it has runs against it.",
			"To try something different, add the next version to that registry and regenerate.",
			"-->",
			"",
			`> **Pass-one splitting prompt \`${version.id}\`.** ${version.summary}`,
			">",
			`> *Changed:* ${version.changed}`,
			"",
			"---",
			"",
			prompt,
			"",
		].join("\n"),
		"utf8",
	);
	console.log(`${name} written`);
}
