"""Regenerate GROUPING-RESULTS.md from the run files.

Every number in the ledger is computed here, so the ledger can never drift from
the runs it describes. Structure (topic counts, sizes, cost, latency) comes from
each run's outcome file; the five criteria are hand judgements and live in
runs/criteria.json, keyed by run stem.

Usage: python3 report-grouping.py
"""

import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RUNS = os.path.join(HERE, "runs")
LEDGER = os.path.join(HERE, "GROUPING-RESULTS.md")

# OpenRouter list price for the Gemini Flash models these trials use, per token.
PRICE_IN, PRICE_OUT = 0.75e-6, 3.75e-6

# A topic this large is the known collapse: pathogens, mutagens and promotion
# swallowed into one heading. Counted because it is detectable without judgement.
MEGA_TOPIC = 8

CRITERIA = [
    ("pathogensSeparate", "pathogens a separate topic"),
    ("promotionOwnTopic", "promotion its own topic"),
    ("uvOwnSubtopic", "UV its own subtopic"),
    ("animalVsAmes", "in vivo vs Ames separate"),
    ("preambleSeparate", "preamble separated"),
]


def load():
    """Every usable run, grouped by (prompt version, labels shown)."""
    scores = json.load(open(os.path.join(RUNS, "criteria.json")))
    cells = {}
    for path in sorted(glob.glob(os.path.join(RUNS, "group-*.outcome.json"))):
        run = json.load(open(path))
        if run["verdict"] != "OK":
            continue
        stem = os.path.basename(path).rsplit(".outcome.json", 1)[0]
        run["stem"] = stem
        run["scores"] = scores.get(stem)
        cells.setdefault((run["promptVersion"], run["labelsShown"]), []).append(run)
    return cells


def summarise(runs):
    """One row's worth of numbers."""
    sizes = [s for r in runs for s in r["topicSizes"]]
    scored = [r for r in runs if r["scores"]]
    clean = sum(1 for r in scored if all(r["scores"][k] for k, _ in CRITERIA))
    per = {k: sum(1 for r in scored if r["scores"][k]) for k, _ in CRITERIA}
    cost = sum((r["promptTokens"] or 0) * PRICE_IN + (r["completionTokens"] or 0) * PRICE_OUT
               for r in runs)
    return {
        "n": len(runs),
        "scored": len(scored),
        "clean": clean,
        "per": per,
        "topics": (min(r["topics"] for r in runs), max(r["topics"] for r in runs)),
        "mega": sum(1 for s in sizes if s >= MEGA_TOPIC),
        "singletons": sum(1 for s in sizes if s == 1),
        "topicCount": len(sizes),
        "seconds": (min(r["seconds"] for r in runs), max(r["seconds"] for r in runs)),
        "cost": cost / len(runs),
    }


def main():
    cells = load()
    versions = json.load(open(os.path.join(HERE, "group-versions.json")))
    lines = [
        "# Grouping prompt versions and what they scored",
        "",
        "Generated by `report-grouping.py` — do not edit by hand. Structure comes from",
        "the run files; the five criteria are hand judgements in `runs/criteria.json`.",
        "",
        "Pass 1 is always the v3 prompt on `google/gemini-3.7-flash`, and pass 2 groups",
        "its subtopics in a separate call. **Labels** is whether pass 1's subtopic labels",
        "were sent up with the text; they are restored either way, so it changes what the",
        "grouping model sees, not what the reader gets.",
        "",
        "## Results",
        "",
        "| version | labels | runs | all five | " +
        " | ".join(label for _, label in CRITERIA) +
        " | topics | 1-subtopic | 8+ subtopic | $/run |",
        "|---|---|---|---|" + "---|" * len(CRITERIA) + "---|---|---|---|",
    ]
    for (version, labels), runs in sorted(cells.items()):
        s = summarise(runs)
        lines.append(
            f"| **{version}** | {'yes' if labels else 'no'} | {s['n']} | "
            f"**{s['clean']}/{s['scored']}** | "
            + " | ".join(f"{s['per'][k]}/{s['scored']}" for k, _ in CRITERIA)
            + f" | {s['topics'][0]}–{s['topics'][1]}"
            f" | {s['singletons']}/{s['topicCount']}"
            f" | {s['mega']} | ${s['cost']:.3f} |"
        )
    lines += ["", "## What each version is", ""]
    for v in versions:
        lines += [f"### {v['id']} — {v['summary']}", "", f"*Changed:* {v['changed']}", ""]
        cell = [(lab, summarise(cells[(v["id"], lab)])) for lab in (True, False)
                if (v["id"], lab) in cells]
        for labels, s in cell:
            lines.append(
                f"- **labels {'shown' if labels else 'withheld'}**: {s['clean']} of {s['scored']} "
                f"runs met all five; {s['topics'][0]}–{s['topics'][1]} topics, "
                f"{s['singletons']}/{s['topicCount']} single-subtopic, {s['mega']} collapsed; "
                f"{s['seconds'][0]}–{s['seconds'][1]}s, ${s['cost']:.3f} a run."
            )
        lines.append("")
    open(LEDGER, "w").write("\n".join(lines) + "\n")
    print(LEDGER)


if __name__ == "__main__":
    main()
