"""Regenerate GROUPING-RESULTS.md from the run files.

Every number in the ledger is computed here, so the ledger can never drift from
the runs it describes. Structure (topic counts, sizes, cost, latency) comes from
each run's outcome file; the five criteria are hand judgements and live in
runs/criteria.json, keyed by run stem.

Usage: python3 report-grouping.py
"""

import glob
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
RUNS = os.path.join(HERE, "runs")
LEDGER = os.path.join(HERE, "GROUPING-RESULTS.md")

# OpenRouter list price for the Gemini Flash models these trials use, per token.
PRICE_IN, PRICE_OUT = 0.75e-6, 3.75e-6

# A topic this large is the known collapse: pathogens, mutagens and promotion
# swallowed into one heading. Counted because it is detectable without judgement.
MEGA_TOPIC = 8

CRITERIA = [
    ("pathogensSeparate", "pathogens a separate topic"),
    ("promotionOwnTopic", "promotion its own topic"),
    ("uvOwnSubtopic", "UV its own subtopic"),
    ("animalVsAmes", "in vivo vs Ames separate"),
    ("preambleSeparate", "preamble separated"),
]


def pass_one(source_run):
    """Which pass-one prompt version cut the subtopics this run grouped.

    Runs made through `split-trial.mts` name their version in the stem. Runs made
    before pass one was versioned name the harness mode instead, and `hierv3` is
    the mode that sent what is now `s1`.
    """
    parts = source_run.split("-")
    if parts[0] == "split":
        return parts[1]
    if parts[0] == "hierv3":
        return "s1"
    return parts[0]


def load():
    """Every usable run, grouped by (lecture, pass-one version, version, labels).

    Lecture is part of the key because none of these numbers travel between
    transcripts: a topic count, a singleton rate and the five criteria all
    describe one lecture's material. Merging two lectures into a row would report
    an average of two different questions.
    """
    scores = json.load(open(os.path.join(RUNS, "criteria.json")))
    cells = {}
    for path in sorted(glob.glob(os.path.join(RUNS, "group-*.outcome.json"))):
        run = json.load(open(path))
        if run["verdict"] != "OK":
            continue
        stem = os.path.basename(path).rsplit(".outcome.json", 1)[0]
        run["stem"] = stem
        run["scores"] = scores.get(stem)
        key = (run.get("lecture", "unknown"), pass_one(run["sourceRun"]),
               run["promptVersion"], run["labelsShown"])
        cells.setdefault(key, []).append(run)
    return cells


def summarise(runs):
    """One row's worth of numbers."""
    sizes = [s for r in runs for s in r["topicSizes"]]
    scored = [r for r in runs if r["scores"]]
    clean = sum(1 for r in scored if all(r["scores"][k] for k, _ in CRITERIA))
    per = {k: sum(1 for r in scored if r["scores"][k]) for k, _ in CRITERIA}
    cost = sum((r["promptTokens"] or 0) * PRICE_IN + (r["completionTokens"] or 0) * PRICE_OUT
               for r in runs)
    return {
        "n": len(runs),
        "scored": len(scored),
        "clean": clean,
        "per": per,
        "topics": (min(r["topics"] for r in runs), max(r["topics"] for r in runs)),
        "mega": sum(1 for s in sizes if s >= MEGA_TOPIC),
        "singletons": sum(1 for s in sizes if s == 1),
        "topicCount": len(sizes),
        "seconds": (min(r["seconds"] for r in runs), max(r["seconds"] for r in runs)),
        "cost": cost / len(runs),
    }


def scored_cell(s, key):
    """One criterion's tally, or a dash where the lecture has no hand judgements."""
    return "—" if s["scored"] == 0 else f"{s['per'][key]}/{s['scored']}"


def main():
    cells = load()
    versions = json.load(open(os.path.join(HERE, "group-versions.json")))
    lectures = sorted({lecture for lecture, *_ in cells})
    lines = [
        "# Grouping prompt versions and what they scored",
        "",
        "Generated by `report-grouping.py` — do not edit by hand. Structure comes from",
        "the run files; the five criteria are hand judgements in `runs/criteria.json`.",
        "",
        "Every table below is **one lecture**. None of these numbers travel between",
        "transcripts — a topic count, a singleton rate and the five criteria all describe",
        "one lecture's material — so runs are never pooled across lectures.",
        "",
        "**Pass 1** names the splitting prompt version from `split-prompts.mts` that cut",
        "the subtopics; **pass 2** groups them in a separate call. **Labels** is whether",
        "pass 1's subtopic labels were sent up with the text; they are restored either",
        "way, so it changes what the grouping model sees, not what the reader gets. Both",
        "passes run on `google/gemini-3.7-flash`.",
        "",
        "The five criteria are lecture 4's rubric, taken from the user's critique of run",
        "h4. A lecture with no rubric of its own scores `—`, which means unjudged, not",
        "failed.",
        "",
        "## Results",
        "",
    ]
    header = ("| pass 1 | pass 2 | labels | runs | all five | " +
              " | ".join(label for _, label in CRITERIA) +
              " | topics | 1-subtopic | 8+ subtopic | $/run |")
    rule = "|---|---|---|---|---|" + "---|" * len(CRITERIA) + "---|---|---|---|"
    for lecture in lectures:
        lines += [f"### Lecture {lecture.lstrip('l') or lecture}", "", header, rule]
        for (_, first, version, labels), runs in sorted(
                (k, v) for k, v in cells.items() if k[0] == lecture):
            s = summarise(runs)
            clean = "—" if s["scored"] == 0 else f"**{s['clean']}/{s['scored']}**"
            lines.append(
                f"| {first} | **{version}** | {'yes' if labels else 'no'} | {s['n']} | "
                f"{clean} | "
                + " | ".join(scored_cell(s, k) for k, _ in CRITERIA)
                + f" | {s['topics'][0]}–{s['topics'][1]}"
                f" | {s['singletons']}/{s['topicCount']}"
                f" | {s['mega']} | ${s['cost']:.3f} |"
            )
        lines.append("")
    lines += ["## What each version is", ""]
    for v in versions:
        lines += [f"### {v['id']} — {v['summary']}", "", f"*Changed:* {v['changed']}", ""]
        for key in sorted(k for k in cells if k[2] == v["id"]):
            lecture, first, _, labels = key
            s = summarise(cells[key])
            met = ("unjudged" if s["scored"] == 0
                   else f"{s['clean']} of {s['scored']} runs met all five")
            lines.append(
                f"- **{lecture}, pass 1 {first}, labels "
                f"{'shown' if labels else 'withheld'}**: {met}; "
                f"{s['topics'][0]}–{s['topics'][1]} topics, "
                f"{s['singletons']}/{s['topicCount']} single-subtopic, {s['mega']} collapsed; "
                f"{s['seconds'][0]}–{s['seconds'][1]}s, ${s['cost']:.3f} a run."
            )
        lines.append("")
    open(LEDGER, "w").write("\n".join(lines) + "\n")
    print(LEDGER)


if __name__ == "__main__":
    main()
